var namespace_mongo_d_b_1_1_driver_1_1_core_1_1_connection_pools =
[
    [ "IConnectionPool", "interface_mongo_d_b_1_1_driver_1_1_core_1_1_connection_pools_1_1_i_connection_pool.html", "interface_mongo_d_b_1_1_driver_1_1_core_1_1_connection_pools_1_1_i_connection_pool" ],
    [ "IConnectionPoolFactory", "interface_mongo_d_b_1_1_driver_1_1_core_1_1_connection_pools_1_1_i_connection_pool_factory.html", "interface_mongo_d_b_1_1_driver_1_1_core_1_1_connection_pools_1_1_i_connection_pool_factory" ]
];